import 'package:geometry_dash/core/constants/levels/level_object.dart';
import './level.dart';

final level48 = Level(
  endColumn: 172,
  objects: [
    // Opening: ring over spikes
    LevelObject(type: LevelObjectType.spike, column: 12, row: 0),
    LevelObject(type: LevelObjectType.spike, column: 13.2, row: 0),
    LevelObject(type: LevelObjectType.jumpRing, column: 15, row: 3.5),
    LevelObject(type: LevelObjectType.platform, column: 18, row: 2, columns: 3.5, rows: .5),
    LevelObject(type: LevelObjectType.spike, column: 23, row: 0),
    LevelObject(type: LevelObjectType.jumpPad, column: 26, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 30, row: 1.5, columns: 4, rows: .5),
    LevelObject(type: LevelObjectType.diamond, column: 32, row: 4),

    LevelObject(type: LevelObjectType.shield, column: 38, row: 1.1),
    LevelObject(type: LevelObjectType.spike, column: 41, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 44, row: 0, columns: 1, rows: 2.5),
    LevelObject(type: LevelObjectType.spike, column: 45.2, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 47, row: 2, columns: 4, rows: .5),
    LevelObject(type: LevelObjectType.jumpRing, column: 53, row: 4),
    LevelObject(type: LevelObjectType.speedPortal, column: 58, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 61, row: 1.5, columns: 4.5, rows: .5),

    LevelObject(type: LevelObjectType.diamond, column: 64, row: 5),
    LevelObject(type: LevelObjectType.spike, column: 70, row: 0),
    LevelObject(type: LevelObjectType.jumpPad, column: 74, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 78, row: 2, columns: 4, rows: .5),
    LevelObject(type: LevelObjectType.spike, column: 84, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 87, row: 1.2, columns: 5, rows: .5),
    LevelObject(type: LevelObjectType.jumpRing, column: 93, row: 4),
    LevelObject(type: LevelObjectType.spike, column: 97, row: 0),
    LevelObject(type: LevelObjectType.spike, column: 98.1, row: 0),

    LevelObject(type: LevelObjectType.speedPortal, column: 102, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 105, row: 0, columns: 1, rows: 3),
    LevelObject(type: LevelObjectType.spike, column: 106.2, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 108, row: 1.5, columns: 4.5, rows: .5),
    LevelObject(type: LevelObjectType.diamond, column: 110.5, row: 5),
    LevelObject(type: LevelObjectType.jumpPad, column: 116, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 120, row: 2, columns: 4, rows: .5),
    LevelObject(type: LevelObjectType.jumpRing, column: 126, row: 4),
    LevelObject(type: LevelObjectType.spike, column: 131, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 134, row: 1.5, columns: 5, rows: .5),
    LevelObject(type: LevelObjectType.diamond, column: 138, row: 4),
    LevelObject(type: LevelObjectType.spike, column: 144, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 147, row: 0, columns: 1, rows: 2.5),
    LevelObject(type: LevelObjectType.platform, column: 150, row: 2, columns: 4, rows: .5),
    LevelObject(type: LevelObjectType.jumpRing, column: 156, row: 4),
    LevelObject(type: LevelObjectType.spike, column: 161, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 164, row: 0, columns: 5, rows: .5),
    LevelObject(type: LevelObjectType.diamond, column: 168, row: 4),
  ],
);
