import 'package:geometry_dash/core/constants/levels/level_object.dart';
import './level.dart';

final level50 = Level(
  endColumn: 180,
  objects: [
    // Opening: finale mixed gauntlet
    LevelObject(type: LevelObjectType.platform, column: 12, row: 0, columns: 1, rows: 2),
    LevelObject(type: LevelObjectType.spike, column: 13.2, row: 0),
    LevelObject(type: LevelObjectType.jumpRing, column: 16, row: 3),
    LevelObject(type: LevelObjectType.jumpPad, column: 20, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 24, row: 2, columns: 3.5, rows: .5),
    LevelObject(type: LevelObjectType.spike, column: 29, row: 0),
    LevelObject(type: LevelObjectType.spike, column: 30.1, row: 0),
    LevelObject(type: LevelObjectType.speedPortal, column: 34, row: 0),

    LevelObject(type: LevelObjectType.platform, column: 37, row: 1.5, columns: 4, rows: .5),
    LevelObject(type: LevelObjectType.shield, column: 42, row: 2.8),
    LevelObject(type: LevelObjectType.diamond, column: 39, row: 4),
    LevelObject(type: LevelObjectType.jumpRing, column: 46, row: 4),
    LevelObject(type: LevelObjectType.platform, column: 49, row: 0, columns: 1, rows: 2.5),
    LevelObject(type: LevelObjectType.spike, column: 50.2, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 52, row: 2, columns: 4, rows: .5),
    LevelObject(type: LevelObjectType.jumpPad, column: 58, row: 0),

    LevelObject(type: LevelObjectType.spike, column: 62, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 65, row: 1.2, columns: 5, rows: .5),
    LevelObject(type: LevelObjectType.jumpRing, column: 71, row: 4),
    LevelObject(type: LevelObjectType.diamond, column: 73, row: 5),
    LevelObject(type: LevelObjectType.speedPortal, column: 78, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 81, row: 0, columns: 1, rows: 3),
    LevelObject(type: LevelObjectType.spike, column: 82.2, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 84, row: 1.5, columns: 4.5, rows: .5),
    LevelObject(type: LevelObjectType.spike, column: 90, row: 0),
    LevelObject(type: LevelObjectType.spike, column: 91.1, row: 0),

    LevelObject(type: LevelObjectType.jumpPad, column: 95, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 99, row: 2, columns: 4, rows: .5),
    LevelObject(type: LevelObjectType.jumpRing, column: 105, row: 4),
    LevelObject(type: LevelObjectType.diamond, column: 107, row: 5),
    LevelObject(type: LevelObjectType.spike, column: 113, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 116, row: 1.5, columns: 5, rows: .5),
    LevelObject(type: LevelObjectType.speedPortal, column: 123, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 126, row: 0, columns: 1, rows: 2.5),
    LevelObject(type: LevelObjectType.platform, column: 128.5, row: 0, columns: 1, rows: 3),
    LevelObject(type: LevelObjectType.jumpRing, column: 133, row: 4),
    LevelObject(type: LevelObjectType.platform, column: 136, row: 2, columns: 4.5, rows: .5),
    LevelObject(type: LevelObjectType.diamond, column: 138.5, row: 5),

    LevelObject(type: LevelObjectType.spike, column: 145, row: 0),
    LevelObject(type: LevelObjectType.jumpPad, column: 149, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 153, row: 1.2, columns: 5, rows: .5),
    LevelObject(type: LevelObjectType.jumpRing, column: 159, row: 4),
    LevelObject(type: LevelObjectType.spike, column: 164, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 167, row: 2, columns: 4, rows: .5),
    LevelObject(type: LevelObjectType.diamond, column: 169, row: 5),
    LevelObject(type: LevelObjectType.spike, column: 175, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 178, row: 0, columns: 2, rows: .5),
  ],
);
