import 'package:geometry_dash/core/constants/levels/level_object.dart';
import './level.dart';

final level49 = Level(
  endColumn: 174.5,
  objects: [
    // Opening: pad into portal
    LevelObject(type: LevelObjectType.jumpPad, column: 13, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 17, row: 2, columns: 3.5, rows: .5),
    LevelObject(type: LevelObjectType.speedPortal, column: 22, row: 0),
    LevelObject(type: LevelObjectType.spike, column: 25, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 28, row: 1.5, columns: 4, rows: .5),
    LevelObject(type: LevelObjectType.diamond, column: 30, row: 4),
    LevelObject(type: LevelObjectType.jumpRing, column: 35, row: 3),

    LevelObject(type: LevelObjectType.shield, column: 40, row: 2.0),
    LevelObject(type: LevelObjectType.spike, column: 43, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 46, row: 0, columns: 1, rows: 2.5),
    LevelObject(type: LevelObjectType.spike, column: 47.2, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 49, row: 2, columns: 4, rows: .5),
    LevelObject(type: LevelObjectType.jumpPad, column: 55, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 59, row: 1.2, columns: 5, rows: .5),
    LevelObject(type: LevelObjectType.jumpRing, column: 65, row: 4),

    LevelObject(type: LevelObjectType.diamond, column: 67, row: 5),
    LevelObject(type: LevelObjectType.spike, column: 73, row: 0),
    LevelObject(type: LevelObjectType.spike, column: 74.1, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 77, row: 1.5, columns: 4.5, rows: .5),
    LevelObject(type: LevelObjectType.speedPortal, column: 83, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 86, row: 0, columns: 1, rows: 3),
    LevelObject(type: LevelObjectType.spike, column: 87.2, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 89, row: 2, columns: 4, rows: .5),
    LevelObject(type: LevelObjectType.jumpRing, column: 95, row: 4),

    LevelObject(type: LevelObjectType.diamond, column: 97, row: 5),
    LevelObject(type: LevelObjectType.jumpPad, column: 103, row: 0),
    LevelObject(type: LevelObjectType.spike, column: 107, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 110, row: 1.5, columns: 5, rows: .5),
    LevelObject(type: LevelObjectType.jumpRing, column: 116, row: 4),
    LevelObject(type: LevelObjectType.platform, column: 119, row: 2, columns: 4.5, rows: .5),
    LevelObject(type: LevelObjectType.diamond, column: 121.5, row: 5),
    LevelObject(type: LevelObjectType.spike, column: 128, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 131, row: 0, columns: 1, rows: 2.5),
    LevelObject(type: LevelObjectType.spike, column: 132.2, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 134, row: 1.5, columns: 4.5, rows: .5),
    LevelObject(type: LevelObjectType.jumpPad, column: 140, row: 0),
    LevelObject(type: LevelObjectType.speedPortal, column: 145, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 148, row: 2, columns: 4, rows: .5),
    LevelObject(type: LevelObjectType.jumpRing, column: 154, row: 4),
    LevelObject(type: LevelObjectType.spike, column: 159, row: 0),
    LevelObject(type: LevelObjectType.platform, column: 162, row: 0, columns: 5, rows: .5),
    LevelObject(type: LevelObjectType.diamond, column: 166, row: 4),
    LevelObject(type: LevelObjectType.platform, column: 170, row: 1.5, columns: 4, rows: .5),
  ],
);
